default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') {"graphqldb_development"} %>
  port: <%= ENV.fetch('DATABASE_PORT') {"5432"} %>
  host: <%= ENV.fetch('DATABASE_HOST') {"localhost"} %>
  username: <%= ENV.fetch('DATABASE_USERNAME') {"postgres"} %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') {"password123"} %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') {"graphqldb_test"} %>
  port: <%= ENV.fetch('DATABASE_PORT') {"5432"} %>
  host: <%= ENV.fetch('DATABASE_HOST') {"localhost"} %>
  username: <%= ENV.fetch('DATABASE_USERNAME') {"postgres"} %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') {"password123"} %>

production:
  <<: *default
